name: myenv
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - scikit-learn=0.20.1
  - pytorch=1.3.1
  - torchvision=0.4.2
  - pip:
    - flake8==3.7.9
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
    - scikit-image==0.14.1
    - opencv-python

